### ISSUE TITLE
Copy an Entire File - server side perms

### ISSUE THREAD

**Issue by olehermanse** [nickanderson/CFEngine-zero-to-hero-primer#3]
@nickanderson Correct me if I'm wrong, but the example **Copy an Entire File** won't work if a beginner attempts it, since you need to set perms in a server bundle. This should at least be mentioned.

**Comment by nickanderson** [comment]
Thanks!

https://github.com/nickanderson/CFEngine-zero-to-hero-primer/commit/87eb46611b6fab96827214dbd783e5634bf04c05#diff-46dad54bdf026fabed1ba5d79e74dc38L577
